// Code generated by "stringer -type=PropertyType"; DO NOT EDIT

package datastore

import "fmt"

const _PropertyTypeName = "PTNullPTIntPTTimePTBoolPTBytesPTStringPTFloatPTGeoPointPTKeyPTBlobKeyPTUnknown"

var _PropertyTypeIndex = [...]uint8{0, 6, 11, 17, 23, 30, 38, 45, 55, 60, 69, 78}

func (i PropertyType) String() string {
	if i >= PropertyType(len(_PropertyTypeIndex)-1) {
		return fmt.Sprintf("PropertyType(%d)", i)
	}
	return _PropertyTypeName[_PropertyTypeIndex[i]:_PropertyTypeIndex[i+1]]
}
