// Code generated by "stringer -type=Toggle"; DO NOT EDIT

package datastore

import "fmt"

const _ToggleName = "AutoOnOff"

var _ToggleIndex = [...]uint8{0, 4, 6, 9}

func (i Toggle) String() string {
	if i >= Toggle(len(_ToggleIndex)-1) {
		return fmt.Sprintf("Toggle(%d)", i)
	}
	return _ToggleName[_ToggleIndex[i]:_ToggleIndex[i+1]]
}
